"""The plan follows the real week.

`BRAINSTORM-miglioramenti-e-gamification.md` §0.4: adaptation starts from precise events
-- pain, a session that was too much, a tired body, a bad morning, a skipped or very
different session, a new threshold -- not from a nightly rewrite. Two responses:

- **soften** (instant, local): the next hard sessions of the affected days become their
  easy version, same day (`move_check.adapt`). Pain or a bad night concerns a day or two;
  rewriting three weeks for it would be the nightly rewrite the brainstorming rules out.
- **replan**: the window from tomorrow is regenerated by the plan generator, because a
  skipped or very different session changes the week's arithmetic -- exactly what the
  generator already handles.

The user's mode decides whether it is applied (with an undo) or proposed. Sessions the
user edited are never touched (§0.4 rule 5): a rule that would soften one reports it.
"""

from __future__ import annotations

import dataclasses
import logging
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from datetime import date as date_type
from datetime import timedelta
from typing import TYPE_CHECKING, Any
from uuid import uuid4

from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

from . import plan_rules
from .checkin import CheckIn
from .move_check import adapt
from .plan_generator import session_from_dict, session_to_dict

if TYPE_CHECKING:
    from .levels import DayTraining

logger = logging.getLogger(__name__)

LOOKBACK_DAYS = 3
SOFTEN_DAYS = 2
MIN_SKIPPED_MINUTES = 30
UNDER_SHARE = 0.5
OVER_SHARE = 1.5
THRESHOLD_CHANGE_BPM = 3
HANDLED_DAYS = 14

SOFTEN_KINDS = ("dolore", "troppo", "stanco", "prontezza")
REPLAN_KINDS = ("saltata", "diversa", "soglia")

_DAY_NAMES = ("lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato", "domenica")


def _fmt(day: date_type) -> str:
    return f"{_DAY_NAMES[day.weekday()]} {day.day}"


def _when(day: date_type, today: date_type) -> str:
    return "oggi" if day == today else "ieri" if day == today - timedelta(days=1) else _fmt(day)


@dataclass
class Event:
    kind: str
    day: date_type
    message: str
    # What makes it the same event again: the day, except for the threshold, where it is
    # the new value (a revision seen on Monday and again on Tuesday is one event).
    ref: str | None = None

    @property
    def key(self) -> str:
        return f"{self.kind}:{self.ref or self.day.isoformat()}"


# ---- 1. what happened ---------------------------------------------------------------------


def _running_minutes(session) -> float:
    return plan_rules.session_duration_minutes(session) if session.sport == plan_rules.RUNNING else 0.0


def detect_events(
    *,
    today: date_type,
    planned: Sequence[dict],
    days: Sequence["DayTraining"],
    checkins: Sequence[CheckIn],
    readiness_state: str | None,
    threshold_now: int | None,
    threshold_planned: int | None,
    handled: set[str],
) -> list[Event]:
    """Every event not handled yet. Pure."""
    out: list[Event] = []
    yesterday = today - timedelta(days=1)
    recent = sorted((c for c in checkins if yesterday <= c.date <= today), key=lambda c: c.date, reverse=True)

    pain = next((c for c in recent if c.body == "dolore"), None)
    if pain:
        out.append(Event("dolore", pain.date, f"{pain.pain_phrase()} segnalato {_when(pain.date, today)}"))
    too_much = next((c for c in recent if c.date == yesterday and c.effort == "troppo"), None)
    if too_much:
        out.append(Event("troppo", yesterday, "Ieri la seduta è stata troppo dura, a detta tua"))
    tired = next((c for c in recent if c.body == "stanco"), None)
    if tired and not pain:
        out.append(Event("stanco", tired.date, f"Stanchezza segnalata {_when(tired.date, today)}"))
    if readiness_state == "scarico":
        out.append(Event("prontezza", today, "Stamattina il corpo chiede tregua: la prontezza è molto bassa"))

    trained = {d.day: d for d in days if d.sessions > 0}
    by_day: dict[date_type, list] = {}
    for raw in planned:
        session = session_from_dict(raw)
        by_day.setdefault(session.date, []).append(session)
    for k in range(LOOKBACK_DAYS, 0, -1):
        day = today - timedelta(days=k)
        running = [s for s in by_day.get(day, []) if s.sport == plan_rules.RUNNING]
        if not running:
            continue
        minutes = sum(_running_minutes(s) for s in running)
        hard = any(plan_rules.session_kind(s) in plan_rules.HARD_KINDS for s in running)
        titles = ", ".join(s.title for s in running)
        done = trained.get(day)
        if done is None:
            if hard or minutes >= MIN_SKIPPED_MINUTES:
                out.append(Event("saltata", day, f"{_fmt(day).capitalize()} la seduta del piano ({titles}) è saltata"))
        elif minutes > 0 and not UNDER_SHARE * minutes <= done.run_minutes <= OVER_SHARE * minutes:
            out.append(
                Event(
                    "diversa",
                    day,
                    f"{_fmt(day).capitalize()} hai corso {round(done.run_minutes)} minuti contro i {round(minutes)} del piano",
                )
            )

    if threshold_now and threshold_planned and abs(threshold_now - threshold_planned) >= THRESHOLD_CHANGE_BPM:
        out.append(
            Event(
                "soglia",
                today,
                f"Garmin ha aggiornato la tua soglia: da {threshold_planned} a {threshold_now} bpm, i ritmi vanno riscritti",
                ref=str(threshold_now),
            )
        )
    return [e for e in out if e.key not in handled]


# ---- 2. what to do ------------------------------------------------------------------------


def soften_days(events: Sequence[Event], today: date_type, sessions: Sequence[dict], trained_today: bool) -> dict[date_type, str]:
    """The days whose hard sessions become easy, with the reason."""
    first = today + timedelta(days=1) if trained_today else today
    hard_days = sorted(
        {
            date_type.fromisoformat(s["date"])
            for s in sessions
            if first.isoformat() <= s["date"] <= (today + timedelta(days=SOFTEN_DAYS)).isoformat()
            and plan_rules.session_kind(session_from_dict(s)) in plan_rules.HARD_KINDS
        }
    )
    out: dict[date_type, str] = {}
    for event in events:
        if event.kind == "dolore":
            for day in hard_days:
                out.setdefault(day, event.message)
        elif event.kind in SOFTEN_KINDS and hard_days:
            out.setdefault(hard_days[0], event.message)
    return out


@dataclass
class DayChange:
    date: date_type
    before: list[str]
    after: list[str]
    reason: str


@dataclass
class Proposal:
    events: list[Event]
    changes: list[DayChange]
    conflicts: list[str]
    # How to apply: an optional window replace, and per-session content updates.
    ops: dict[str, Any]
    # How to undo it the same day.
    undo: dict[str, Any]
    source: str | None = None


def _content(session: dict) -> dict:
    return {k: session.get(k) for k in ("date", "sport", "title", "description", "steps")}


def build_proposal(
    *,
    events: Sequence[Event],
    today: date_type,
    stored: Sequence[dict],
    trained_today: bool,
    replan: Callable[[], Any] | None = None,
) -> Proposal:
    """What the events ask for. `replan` is the generator's dry run, called only when a
    replan event is among them. Pure apart from that call."""
    replace = None
    source = None
    after_state = [dict(s) for s in stored]
    replan_reason = "; ".join(e.message for e in events if e.kind in REPLAN_KINDS)
    if replan_reason and replan is not None:
        result = replan()
        start, end = result.window.start, result.window.end
        kept = [s for s in after_state if not (start.isoformat() <= s["date"] <= end.isoformat() and not s["locked"])]
        proposed = [{**session_to_dict(s), "id": None, "locked": False} for s in result.proposed]
        after_state = kept + proposed
        replace = {"start": start, "end": end, "expected": result.expected}
        source = result.source

    to_soften = soften_days(events, today, after_state, trained_today)
    conflicts: list[str] = []
    updates: list[dict] = []
    for session in after_state:
        day = date_type.fromisoformat(session["date"])
        if day not in to_soften or plan_rules.session_kind(session_from_dict(session)) not in plan_rules.HARD_KINDS:
            continue
        if session.get("locked"):
            conflicts.append(
                f"{_fmt(day).capitalize()} ({session['title']}) l'hai scelta tu, quindi resta: con {to_soften[day].lower()}, valuta tu se alleggerirla"
            )
            continue
        easy = session_to_dict(adapt(session_from_dict(session)))
        # A session kept from the plan is updated in place; one inside a replaced window
        # is written softened by the replace itself.
        if session.get("id") is not None and not _in(day, replace):
            updates.append({"id": session["id"], "content": _content(easy), "before": _content(session)})
        session.update({k: easy[k] for k in ("title", "description", "steps")})
        session["_softened"] = to_soften[day]

    # What the user sees: per day, the titles before and after.
    changes: list[DayChange] = []
    days = sorted({s["date"] for s in (*stored, *after_state)})
    for iso in days:
        day = date_type.fromisoformat(iso)
        before = [s["title"] for s in stored if s["date"] == iso]
        after = [s["title"] for s in after_state if s["date"] == iso]
        if before == after:
            continue
        softened = next((s["_softened"] for s in after_state if s["date"] == iso and "_softened" in s), None)
        reason = f"Alleggerita: {softened.lower()}" if softened else f"Riscritta: {replan_reason.lower()}"
        changes.append(DayChange(day, before, after, reason))

    ops: dict[str, Any] = {"updates": [{"id": u["id"], "content": u["content"]} for u in updates]}
    undo: dict[str, Any] = {"updates": [{"id": u["id"], "content": u["before"]} for u in updates]}
    if replace is not None:
        start, end = replace["start"], replace["end"]
        ops["replace"] = {
            "start": start.isoformat(),
            "end": end.isoformat(),
            "sessions": [
                {k: v for k, v in s.items() if k not in ("id", "locked", "_softened", "origin")}
                for s in after_state
                if start.isoformat() <= s["date"] <= end.isoformat() and not s.get("locked")
            ],
            "expected": [replace["expected"][0].isoformat(), replace["expected"][1].isoformat(), replace["expected"][2]],
        }
        undo["replace"] = {
            "start": start.isoformat(),
            "end": end.isoformat(),
            "sessions": [
                _content(s) for s in stored if start.isoformat() <= s["date"] <= end.isoformat() and not s["locked"]
            ],
        }
    for s in after_state:
        s.pop("_softened", None)
    return Proposal(list(events), changes, conflicts, ops, undo, source)


def _in(day: date_type, replace: dict | None) -> bool:
    return replace is not None and replace["start"] <= day <= replace["end"]


# ---- 3. storage and application -----------------------------------------------------------

SCHEMA = """
CREATE TABLE IF NOT EXISTS plan_adaptation (
    id          UUID PRIMARY KEY,
    user_id     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    day         DATE NOT NULL,
    status      TEXT NOT NULL,
    events      JSONB NOT NULL,
    changes     JSONB NOT NULL,
    conflicts   JSONB NOT NULL,
    ops         JSONB NOT NULL,
    undo        JSONB NOT NULL,
    source      TEXT
);
CREATE INDEX IF NOT EXISTS plan_adaptation_user_idx ON plan_adaptation (user_id, created_at);
"""

# pending: waiting for the user; applied / undone / rejected: answered; none: events
# handled with nothing to change; stale: the plan changed before it was accepted.
STATUSES = ("pending", "applied", "undone", "rejected", "none", "stale")


class AdaptationNotFound(Exception):
    pass


class AdaptationNotPending(Exception):
    pass


def ensure_schema() -> None:
    from . import db

    with db.connect() as conn:
        conn.execute(SCHEMA)


def handled_events(user_id: str, today: date_type) -> set[str]:
    from . import db

    with db.connect() as conn:
        rows = conn.execute(
            "SELECT jsonb_array_elements(events)->>'key' FROM plan_adaptation "
            "WHERE user_id = %s AND day >= %s AND status <> 'stale'",
            [user_id, today - timedelta(days=HANDLED_DAYS)],
        ).fetchall()
    return {row[0] for row in rows}


def _record(user_id: str, today: date_type, proposal: Proposal, status: str) -> dict:
    from . import db

    row_id = str(uuid4())
    changes = [
        {"date": c.date.isoformat(), "before": c.before, "after": c.after, "reason": c.reason} for c in proposal.changes
    ]
    events = [{"key": e.key, "kind": e.kind, "day": e.day.isoformat(), "message": e.message} for e in proposal.events]
    with db.connect() as conn:
        conn.execute(
            """INSERT INTO plan_adaptation (id, user_id, day, status, events, changes, conflicts, ops, undo, source)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            [
                row_id, user_id, today, status, Jsonb(events), Jsonb(changes), Jsonb(proposal.conflicts),
                Jsonb(proposal.ops), Jsonb(proposal.undo), proposal.source,
            ],
        )
    return get(user_id, row_id)


def get(user_id: str, row_id: str) -> dict:
    from . import db

    with db.connect() as conn, conn.cursor(row_factory=dict_row) as cur:
        cur.execute("SELECT * FROM plan_adaptation WHERE user_id = %s AND id = %s", [user_id, row_id])
        row = cur.fetchone()
    if row is None:
        raise AdaptationNotFound(row_id)
    return row


def current(user_id: str, today: date_type) -> dict | None:
    """The pending proposal, or the adaptation applied today (for its undo)."""
    from . import db

    with db.connect() as conn, conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            "SELECT * FROM plan_adaptation WHERE user_id = %s AND "
            "(status = 'pending' OR (status = 'applied' AND day = %s)) ORDER BY created_at DESC LIMIT 1",
            [user_id, today],
        )
        return cur.fetchone()


def _set_status(user_id: str, row_id: str, status: str) -> dict:
    from . import db

    with db.connect() as conn:
        conn.execute("UPDATE plan_adaptation SET status = %s WHERE user_id = %s AND id = %s", [status, user_id, row_id])
    return get(user_id, row_id)


def _apply(user_id: str, ops: dict, *, check_expected: bool) -> None:
    from . import plan_store

    replace = ops.get("replace")
    if replace:
        expected = None
        if check_expected and replace.get("expected"):
            since, until, seen = replace["expected"]
            expected = (date_type.fromisoformat(since), date_type.fromisoformat(until), seen)
        plan_store.replace_unlocked(
            user_id,
            date_type.fromisoformat(replace["start"]),
            date_type.fromisoformat(replace["end"]),
            replace["sessions"],
            origin="ai",
            expected=expected,
        )
    for update in ops.get("updates", []):
        try:
            plan_store.update_session(user_id, update["id"], update["content"], by_user=False)
        except (plan_store.SessionLocked, plan_store.SessionNotFound):
            # The user got to it first: their version wins.
            logger.info("adaptation skipped session %s: changed by the user", update["id"])


def accept(user_id: str, row_id: str) -> dict:
    from . import plan_store

    row = get(user_id, row_id)
    if row["status"] != "pending":
        raise AdaptationNotPending(row_id)
    try:
        _apply(user_id, row["ops"], check_expected=True)
    except plan_store.PlanChanged:
        return _set_status(user_id, row_id, "stale")
    return _set_status(user_id, row_id, "applied")


def reject(user_id: str, row_id: str) -> dict:
    row = get(user_id, row_id)
    if row["status"] != "pending":
        raise AdaptationNotPending(row_id)
    return _set_status(user_id, row_id, "rejected")


def undo(user_id: str, row_id: str, today: date_type) -> dict:
    row = get(user_id, row_id)
    if row["status"] != "applied" or row["day"] != today:
        raise AdaptationNotPending(row_id)
    _apply(user_id, row["undo"], check_expected=False)
    return _set_status(user_id, row_id, "undone")


def run_check(
    user_id: str,
    today: date_type,
    *,
    days: Sequence["DayTraining"],
    checkins: Sequence[CheckIn],
    readiness_state: str | None,
    threshold_now: int | None,
    mode: str,
    replan: Callable[[], Any],
) -> dict | None:
    """Detect, respond, and apply or propose. Returns the stored adaptation, or None when
    nothing new happened. The caller holds the generation lock."""
    from . import db, plan_store

    skeleton = db.get_skeleton(user_id) or {}
    threshold_planned = skeleton.get("threshold_hr")
    if threshold_now and not threshold_planned and skeleton:
        # First look since the threshold started being recorded: remember it, no event.
        db.save_skeleton(user_id, {**skeleton, "threshold_hr": threshold_now})

    stored = plan_store.list_sessions(user_id)
    events = detect_events(
        today=today,
        planned=stored,
        days=days,
        checkins=checkins,
        readiness_state=readiness_state,
        threshold_now=threshold_now,
        threshold_planned=threshold_planned,
        handled=handled_events(user_id, today),
    )
    if not events:
        return None
    trained_today = any(d.day == today and d.sessions > 0 for d in days)
    needs_replan = any(e.kind in REPLAN_KINDS for e in events) and any(s["date"] > today.isoformat() for s in stored)
    proposal = build_proposal(
        events=events,
        today=today,
        stored=stored,
        trained_today=trained_today,
        replan=replan if needs_replan else None,
    )
    if not proposal.changes and not proposal.conflicts:
        _record(user_id, today, proposal, "none")
        return None
    if mode == "automatico" and proposal.changes:
        try:
            _apply(user_id, proposal.ops, check_expected=True)
        except plan_store.PlanChanged:
            return None  # the user is editing right now: look again next time
        if threshold_now:
            fresh = db.get_skeleton(user_id) or {}
            if fresh:
                db.save_skeleton(user_id, {**fresh, "threshold_hr": threshold_now})
        return _record(user_id, today, proposal, "applied")
    return _record(user_id, today, proposal, "pending")
